### ISSUE TITLE
Nethunter compatability

### ISSUE THREAD

**Issue by ozsteyr** [evilsocket/bettercap-ng#21]
Is Bettercap-ng compatable within Nethunter? I ask due to errors. #
![screenshot_20180117-121548](https://user-images.githubusercontent.com/13267324/35021465-ed4a5864-fb80-11e7-8e88-334a0aa3fcf2.jpg)

**Comment by evilsocket** [comment]
1. "Compatible with Nethunter" doesn't mean anything.
2. That's a compilation problem of the pcap library.
3. Learn to understand what you use.
4. The screenshot is the very answer to your own question.
