### ISSUE TITLE
Adding tiles in order to separate the events stream from the interactive session?

### ISSUE THREAD

**Issue by naltun** [evilsocket/bettercap-ng#36]
### Prerequisites

* [x] I read the [README](https://github.com/evilsocket/bettercap-ng/blob/master/README.md).
* [x] I am running the [latest source code version](https://github.com/evilsocket/bettercap-ng).
* [x] I already searched [other issues](https://github.com/evilsocket/bettercap-ng/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported.

### Description

*FEATURE REQUEST*
The ability to separate 'actions' into tiles in the terminal (or maybe implementing curses). I find the `events.stream` can be a bit burdensome at times when I am wanting to focus on a task and events keep streaming. Nothing is stopping me from opening up a separate tile and running `bettercap-ng` with `events.stream off`, but if I could do it all in `bettercap-ng`, then even better. :grin:

I am thinking of being able to dedicate an entire tile in `bettercap-ng` to `events.stream`, and the other tile can be used for issuing commands, etc.

### Environment

Please provide:

* OS version and architecture you are using.
Antergos Linux (x86_64)
* Command line arguments you are using.
None
* Caplet code you are using (if any).
None
* Interactive session commands you are using (if any).
Most of them

### Steps to Reproduce
N/A

**Expected behavior:** *What you expected to happen*
N/A
**Actual behavior:** *What actually happened*
N/A
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
Curses is out of question, regarding "separate 'actions" into tiles in the terminal" could you please be clearer? I did not understand exactly what you want.

As you mentioned, if you have a lot of events, you can just pause the stream with `events.stream off`, inspect it with `events.show` and then resume with `events.stream on` ...

**Comment by evilsocket** [comment]
I see. That would require some TUI, while the main logic of bettercap-ng is a metasploit-like interactive session. I guess that would be more adeguate as some external UI tool using bettercap's `api.rest` module. I'm sorry but implementing this feature would basically break the interactive session logic, will close.

**Comment by evilsocket** [comment]
it's not -exactly- what you asked for, but now `net.show` will print the last 20 events, try to use `netmon.cap` now :)

**Comment by naltun** [comment]
Awesome, mate! Were you planning on removing the histogram?
I like the feature of showing the last 20 events. Makes it real easy for me to see the latest after I haven't been monitoring in a while.

**Comment by evilsocket** [comment]
Not planning, but you gave me a reason to think about it, and that space is better used for network events! :D
