### ISSUE TITLE
[bug/net.sniff] Truncated stats console output

### ISSUE THREAD

**Issue by dimorphic** [evilsocket/bettercap-ng#37]
### Prerequisites

* [x] I read the [README](https://github.com/evilsocket/bettercap-ng/blob/master/README.md).
* [x] I am running the [latest source code version](https://github.com/evilsocket/bettercap-ng).
* [x] I already searched [other issues](https://github.com/evilsocket/bettercap-ng/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported.

### Description

Running `net.sniff stats` truncates the output in console (other modules affected also maybe ?)

### Environment

- OS: OSX 10.11.6
- CLI args: none
- Caplet: none
- Debug output: https://pastebin.com/geYzz1HN

### Steps to Reproduce

1. `sudo bettercap-ng`
2. `net.sniff on`
3. `net.sniff stats`
4. Observe output is 'truncated' (1 line)
5. `events.show`
6. Check output and look for `[sys.log]` lines (10 lines, not 1)
7. :(

**Expected behavior:** Get output like: 

> [2018-02-01 13:22:10] [sys.log] (inf) Skip local packets : yes
[2018-02-01 13:22:10] [sys.log] (inf) Verbose            : yes
[2018-02-01 13:22:10] [sys.log] (inf) BPF Filter         : 'not arp'
[2018-02-01 13:22:10] [sys.log] (inf) Sniffer Started    : 2018-02-01 13:22:03.560197387 +0200 EET m=+15.772539851
[2018-02-01 13:22:10] [sys.log] (inf) First Packet Seen  : 2018-02-01 13:22:04.7175125 +0200 EET m=+16.929894964
[2018-02-01 13:22:10] [sys.log] (inf) Last Packet Seen   : 2018-02-01 13:22:10.386655374 +0200 EET m=+22.599236838
[2018-02-01 13:22:10] [sys.log] (inf) Local Packets      : 2975
[2018-02-01 13:22:10] [sys.log] (inf) Matched Packets    : 0
[2018-02-01 13:22:10] [sys.log] (inf) Dumped Packets     : 0
[2018-02-01 13:22:10] [sys.log] (inf) Wrote Packets      : 0

**Actual behavior:** Got only first line, rest lost in void?
> [2018-02-01 13:22:10] [sys.log] (inf) Skip local packets : yes

**Comment by dimorphic** [comment]
<3

**Comment by evilsocket** [comment]
:+1:

**Comment by dimorphic** [comment]
I think this introduced a 'regression': i'm now getting `[env.change]` outputs as i start bettercap with no `-debug` flag.

`$ sudo bettercap-ng`
> bettercap-ng v0.9.0
192.168.100.0/24 > 192.168.100.4  » [2018-02-01 14:47:57] [env.change] {env.change 2018-02-01 14:47:57.547113526 +0200 EET m=+0.011070084 {events.stream.filter }}
192.168.100.0/24 > 192.168.100.4  » [2018-02-01 14:47:57] [env.change] {env.change 2018-02-01 14:47:57.547123934 +0200 EET m=+0.011080492 {ticker.commands clear; net.show}}
192.168.100.0/24 > 192.168.100.4  » [2018-02-01 14:47:57] [env.change] {env.change 2018-02-01 14:47:57.547131558 +0200 EET m=+0.011088116 {ticker.period 1}}
192.168.100.0/24 > 192.168.100.4  » [2018-02-01 14:47:57] [env.change] {env.change 2018-02-01 14:47:57.547151821 +0200 EET m=+0.011108379 {mac.changer.address <random mac>}}
192.168.100.0/24 > 192.168.100.4  » [2018-02-01 14:47:57] [env.change] {env.change 2018-02-01 14:47:57.547159964 +0200 EET m=+0.011116522 {net.probe.throttle 10}}
...
192.168.100.0/24 > 192.168.100.4  » [2018-02-01 14:49:42] [session.started] {session.started 2018-02-01 14:49:42.04480419 +0200 EET m=+0.073859028 <nil>}
192.168.100.0/24 > 192.168.100.4  » [2018-02-01 14:49:42] [mod.started] events.stream
192.168.100.0/24 > 192.168.100.4  » [2018-02-01 14:49:42] [mod.started] net.recon
192.168.100.0/24 > 192.168.100.4  » [2018-02-01 14:49:43] [target.new] 192.168.100.2 : 2c:56:dc:39:75:61 ( Asustek Computer )

Expected to see discovered targets first as in the pastebin log above, eg:

> 192.168.100.0/24 > 192.168.100.4  » [2018-02-01 13:21:48] [target.new] 192. [...]

**Comment by evilsocket** [comment]
`env.change` is one type of event and `sys.log` is another one, the `-debug` flag only filters `sys.log` events by their sub level, it does not affect the `events.stream` module.

**Comment by evilsocket** [comment]
basically you see way more stuff now because the bug you spotted prevented all the events from being correctly displayed :D

**Comment by dimorphic** [comment]
Aha! :D 👍

**Comment by evilsocket** [comment]
(maybe i should just change that specific event, it's quite useless tbh)

**Comment by evilsocket** [comment]
https://github.com/evilsocket/bettercap-ng/commit/4756b885ec28a83fc2bedc61abb66e42e0ba7509

**Comment by dimorphic** [comment]
Sweet(er) 🍺

**Comment by evilsocket** [comment]
:beers:

**Comment by dimorphic** [comment]
Minor post-fix : #38 

![meh](https://i.imgur.com/HTisMpC.jpg)

**Comment by evilsocket** [comment]
ahahah fixing that was in my TODO for tonight, thanks for saving me the time! :D
