### ISSUE TITLE
I disabled the prompt, events.stream and sniffer output but for some reason expect output ...

### ISSUE THREAD

**Issue by dimorphic** [evilsocket/bettercap-ng#40]
### Prerequisites

* [x] I read the [README](https://github.com/evilsocket/bettercap-ng/blob/master/README.md).
* [x] I am running the [latest source code version](https://github.com/evilsocket/bettercap-ng).

Almost! I'm having this tweak to not truncate URLs in `modules/net_sniff_http.go` (line 61), which will increase the console output & might cause / increase the triggering of the bug.
> url, // vURL(url)

* [x] I already searched [other issues](https://github.com/evilsocket/bettercap-ng/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported.

### Description

`net.sniff` / console buffer gets stuck, user input ignored, CLI hangs

### Environment

- OS: OSX 10.11.6
- CLI args: none
- Caplet: 

> set $ ""
events.stream off
events.clear
set net.sniff.verbose false
set net.sniff.local true
set net.sniff.filter not arp and not udp port 53
net.sniff on

- Debug output: none

### Steps to Reproduce

1. `sudo bettercap-ng -caplet capture.cap`
2. Open a browser in private mode
3. Go to http://arstechnica.com
4. Go to http://mashable.com
5. Refresh one/both of the websites above (1 or a few times)
...
6. CLI will hang, no more console output, user input will be ignored
7. RIP `sudo kill -9 $(pgrep bettercap-ng)` :(

**Expected behavior:** Output continues as normal & user input is not blocked, CLI doesn't hang

**Actual behavior:** bettercap-ng hangs, no more `net.sniff` / console output and any user input is ignored in the CLI

**Comment by evilsocket** [comment]
> CLI will hang, no more console output, user input will be ignored

You removed the prompt, disabled the events.stream and made the sniffer non verbose, what output do you expect exactly? 

> set $ ""
> events.stream off
> events.clear
> set net.sniff.verbose false

**Comment by dimorphic** [comment]
The normal `net.sniff` (+/- `net.recon`) output that i'm getting as usual before it hangs, as here: [log-output](https://pastebin.com/raw/sGTtk8Vx) (just a small sample).

**Comment by evilsocket** [comment]
if you set `net.sniff.verbose` to false, the sniffer will not print those lines anymore and, since you also put the `events.stream off`, those lines are not gonna be reported as events neither ... again, if you silence pretty much everything and remove the prompt, the result will be that everything will be silenced and without a prompt ...

**Comment by evilsocket** [comment]
it does not "hang", at some point your commands just disable every possible output and so nothing is shown ...

**Comment by dimorphic** [comment]
Mhmm, no ? You have `net.sniff` (and `net.recon`) output until CLI hangs and no more outputs :(

1. `net.sniff.verbose` - "If true, will print every captured packet, otherwise only selected ones" - i only care about my `net.sniff.filter` packets to show up, and don't need these kind, as it's too much/verbose and not needed right now in this caplet i'm running:

> [2018-02-05 16:08:51] tcp 54.77.130.2:http > local:50742 32 bytes
[2018-02-05 16:08:51] tcp 54.77.130.2:http > local:50743 32 bytes
[2018-02-05 16:08:51] tcp 185.133.64.100:http > local:50750 32 bytes
[2018-02-05 16:08:52] tcp 185.133.64.100:http > local:50750 1432 bytes
[2018-02-05 16:08:52] tcp 185.133.64.100:http > local:50750 1432 bytes
[2018-02-05 16:08:52] tcp 185.133.64.100:http > local:50750 1432 bytes
[2018-02-05 16:08:52] tcp 185.133.64.100:http > local:50750 1432 bytes

I only want the `http` & `sni` for now to show up (like in the pastebin log above).

2. `events.stream off` - i don't need the extra events log lines like `net.sniff.leak.*`:
> [2018-02-05 16:12:03] [net.sniff.leak.https] 192.168.100.8 > mashable.com | host=mashable.com
[2018-02-05 16:12:03] [net.sniff.leak.https] 192.168.100.8 > cdn.optimizely.com | host=cdn.optimizely.com
[2018-02-05 16:12:03] [net.sniff.leak.https] 192.168.100.8 > cdn.static.zdbb.net | host=cdn.static.zdbb.net

3. `set $ ""` - because i don't want the prepended prompt IP range at start of lines (eg: `192.168.100.0/24 > 192.168.100.8  »`), like default when running `sudo bettercap-ng`, it's just a 'tidy log output cleanup' example and commands still work, it's not the case.

> 192.168.100.0/24 > 192.168.100.8  » [2018-02-05 16:13:36] [session.started] {session.started 2018-02-05 16:13:36.218173081 +0200 EET m=+0.059502174 <nil>}
192.168.100.0/24 > 192.168.100.8  » [2018-02-05 16:13:36] [mod.started] events.stream
...

This is still a bug imo 🎱

**Comment by evilsocket** [comment]
> You have net.sniff (and net.recon) output until CLI hangs and no more outputs :(

That's because the caplet is not executed right away but *some* of the output has the time to be printed before you disable all of it.

This is not a bug, maybe you know better than me but i'm quite confident that if you disable the output, no output will be shown (after the commands are executed).

Locking this thread as it's becoming a waste of my time.

**Comment by evilsocket** [comment]
https://twitter.com/evilsocket/status/960529516346167296

**Comment by evilsocket** [comment]
Very last time I attempt an explaination.

**Every sniffer related event** [is sent](https://github.com/evilsocket/bettercap-ng/blob/master/modules/net_sniff_event.go#L34) to the `events.stream` module which, if enable, [prints them](https://github.com/evilsocket/bettercap-ng/blob/master/modules/events_view.go#L38). 
Now, if you disable that module ( `events.stream off` ), no matter what other `net.sniff.*` flags are ( verbose or not ), no event will be shown, therefore no output from the sniffer.

Session is still interactive (even if you use an empty prompt), you just won't see any output from your commands.
