### ISSUE TITLE
Can't open caplet no such file or directory

### ISSUE THREAD

**Issue by meeeo** [evilsocket/bettercap-ng#47]
Hi, one simple stupid question:
Why can't I use the -caplet option?
<img width="1440" alt="2018-02-09 17 41 22" src="https://user-images.githubusercontent.com/5188710/36021355-7fb750c0-0dc0-11e8-9984-a863bf249543.png">

Don't know where to ask, sorry for asking here if it's wrong place.

**Comment by ohpe** [comment]
Caplets are not included in the binary. Use `-caplet <path-to-caplet>`

**Comment by evilsocket** [comment]
@meeeo you can't beause you don't understand what you are doing.
