### ISSUE TITLE
implement REST API

### ISSUE THREAD

**Issue by evilsocket** [evilsocket/bettercap-ng#5]
Implement a `api.rest` session module using  `api.rest.username` and `api.rest.password` parameters to expose authenticated REST API:

- [x] **GET /api/session** - Info about current running session, active modules, variables, network, targets, etc.
 - [x] **POST /api/session** - Send commands to the interactive session.
- [x] **GET /api/events/n** - Get last `n` events.
- [x] **DELETE /api/events** - Clear events.
- [ ] HTTPS certificate loading from file.
- [ ] HTTPS certificate generation and dump to `~/.bettercap-ng.certificate.pgm`

**Comment by TahaDgn** [comment]
Guess you ve forgotten to add what those are returning
