### ISSUE TITLE
Problem installing on kali

### ISSUE THREAD

**Issue by madScript01** [evilsocket/bettercap-ng#55]
### Prerequisites

* [x] I read the [README](https://github.com/evilsocket/bettercap-ng/blob/master/README.md).
* [x] I am running the [latest source code version](https://github.com/evilsocket/bettercap-ng).
* [x] I already searched [other issues](https://github.com/evilsocket/bettercap-ng/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported.

### Description
I installed golang with apt and then I installed libpcap-dev and then when after installing bettercap-ng it isn't detected by the system, don't know why. I'm going to send a attached debug of what I actually did...

### Environment

Please provide:

* Kali Linux 2018.1 32 bit

### Steps to Reproduce

[output.txt](https://github.com/evilsocket/bettercap-ng/files/1733063/output.txt)

**Expected behavior:** *What you expected to happen*
Open bettercap-ng
**Actual behavior:** *What actually happened*
It didn't detected as installed don't knowing why
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
It doesn't work because you:

1. Did not RTFM ( `Make sure ... that $GOPATH/bin is in $PATH` ).
2. Do not understand how relative and absolute paths work, or `$PATH`.
