### ISSUE TITLE
wifi.recon does not detect some encryption mechanisms

### ISSUE THREAD

**Issue by evilsocket** [evilsocket/bettercap-ng#57]
wifi.recon does not detect some encryption mechanisms, in which case the encryption column is just empty, we need to investigate and find a way to detect what kind of encryption is going on with those networks.

![schermata del 2018-02-17 15-21-37](https://user-images.githubusercontent.com/86922/36341953-895efbb4-13f6-11e8-9d64-a34ff3c7f9c1.png)

**Comment by Matrix86** [comment]
Sure. I'll try to understand why it happens.

**Comment by evilsocket** [comment]
the issue is still here :(

**Comment by Matrix86** [comment]
Maybe I found the problem, but I need a free moment to fix and verify that!

**Comment by evilsocket** [comment]
if you describe it i can check

**Comment by evilsocket** [comment]
briefly, please

**Comment by Matrix86** [comment]
https://github.com/evilsocket/bettercap-ng/blob/master/packets/dot11.go#L83

In the packet could be more than 1 Vendor layers, maybe the string is overwritten (I verified with wireshark and I saw that the bytes are there)

**Comment by evilsocket** [comment]
can you send me a pcap?

**Comment by Matrix86** [comment]
Nope....I didn't save it xD

**Comment by evilsocket** [comment]
nope

**Comment by evilsocket** [comment]
@Matrix86 when you can please check my latest commit, it looks fixed to me but i can't fully test on my own
