### ISSUE TITLE
error on make

### ISSUE THREAD

**Issue by megahz** [evilsocket/bettercap-ng#8]
hi i get this on make:

session/session.go:184:15: undefined: firewall.Make

**Comment by evilsocket** [comment]
are you building on linux?

**Comment by megahz** [comment]
No Mac:

Darwin andreas-imac 17.4.0 Darwin Kernel Version 17.4.0: Tue Dec 19 11:20:50 PST 2017; root:xnu-4570.41.2~2/RELEASE_X86_64 x86_64

**Comment by evilsocket** [comment]
https://github.com/evilsocket/bettercap-ng/issues/4
